version: '3.8'

services:
  frontend:
    build: ./front
    ports:
      - "3001:3001"
    depends_on:
      - catalog
      - order
    networks:
      - app-network

  catalog:
    build: ./catalog
    ports:
      - "3002:3002"
    volumes:
      - ./catalog:/catalog  # Mount the catalog directory
    networks:
      - app-network

  order:
    build: ./order
    ports:
      - "3003:3003"
    volumes:
      - ./catalog:/catalog  # Mount the same catalog directory for access
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
